### ISSUE TITLE
Typos in "example_data/task1.ttl"

### ISSUE THREAD

**Issue by jplu** [anuzzolese/oke-challenge#1]
Hi,

After analysing the example file for task 1, I saw few typos in the file, so here a corrected  and more readable version:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix d0: <http://ontologydesignpatterns.org/ont/wikipedia/d0.owl#> .
@prefix dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#> .
@prefix oke: <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/> .
@prefix dbpedia: <http://dbpedia.org/resource/> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .

oke:sentence-1
      a nif:Context ;
      nif:isString "Florence May Harding studied at the National Art School in Sydney, and with Douglas Robert Dundas, but in effect had no formal training in either botany or art."@en .

oke:Florence_May_Harding
     a dul:Person ;
     rdfs:label "Florence May Harding"@en ;
     dc:relation oke:0_20_Florence_May_Harding ;
     owl:sameAs dbpedia:Florence_May_Harding .

oke:0_20_Florence_May_Harding
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-1 ;
     nif:beginIndex "0"^^xsd:int ;
     nif:endIndex "20"^^xsd:int .

oke:National_Art_School
     a dul:Organization ;
     rdfs:label "National Art School"@en ;
     dc:relation oke:36_55_National_Art_School ;
     owl:sameAs dbpedia:National_Art_School .

oke:36_55_National_Art_School
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-1 ;
     nif:beginIndex "36"^^xsd:int ;
     nif:endIndex "55"^^xsd:int .

oke:Sydney
     a d0:Location ;
     rdfs:label "Sydney"@en ;
     dc:relation oke:59_65_Sydney ;
     owl:sameAs dbpedia:Sydney .

oke:59_65_Sydney
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-1 ;
     nif:beginIndex "59"^^xsd:int ;
     nif:endIndex "65"^^xsd:int .

oke:Douglas_Robert_Dundas
     a dul:Person ;
     rdfs:label "Douglas Robert Dundas"@en ;
     dc:relation oke:76_97_Douglas_Robert_Dundas .

oke:76_97_Douglas_Robert_Dundas
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-1 ;
     nif:beginIndex "76"^^xsd:int ;
     nif:endIndex "97"^^xsd:int .

oke:sentence-2
      a nif:Context ;
      nif:isString "Such notables include James Carville, who was the senior political adviser to Bill Clinton, and Donna Brazile, the campaign manager of the 2000 presidential campaign of Vice-President Al Gore."@en .

oke:James_Carville
     a dul:Person ;
     rdfs:label "James Carville"@en ;
     dc:relation oke:22_36_James_Carville ;
     owl:sameAs dbpedia:James_Carville .

oke:22_36_James_Carville
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-2 ;
     nif:beginIndex "22"^^xsd:int ;
     nif:endIndex "36"^^xsd:int .

oke:Political_adviser
     a dul:Role ;
     rdfs:label "political adviser"@en ;
     dc:relation oke:54_74_Political_adviser ;
     owl:sameAs dbpedia:Political_consulting .

oke:54_74_Political_adviser
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-2 ;
     nif:beginIndex "54"^^xsd:int ;
     nif:endIndex "74"^^xsd:int .

oke:Bill_Clinton
     a dul:Person ;
     rdfs:label "Bill Clinton"@en ;
     dc:relation oke:78_90_Bill_Clinton ;
     owl:sameAs dbpedia:Bill_Clinton .

oke:78_90_Bill_Clinton
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-2 ;
     nif:beginIndex "78"^^xsd:int ;
     nif:endIndex "90"^^xsd:int .

oke:Donna_Brazile
     a dul:Person ;
     rdfs:label "Donna Brazile"@en ;
     dc:relation oke:96_109_Donna_Brazile ;
     owl:sameAs dbpedia:Donna_Brazile .

oke:96_109_Donna_Brazile
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-2 ;
     nif:beginIndex "96"^^xsd:int ;
     nif:endIndex "109"^^xsd:int .

oke:Campaign_manager
     a dul:Role ;
     rdfs:label "campaign manager"@en ;
     dc:relation oke:115_131_Campaign_manager ;
     owl:sameAs dbpedia:Campaign_manager .

oke:115_131_Campaign_manager
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-2 ;
     nif:beginIndex "115"^^xsd:int ;
     nif:endIndex "131"^^xsd:int .

oke:Al_Gore
     a dul:Person ;
     rdfs:label "campaign manager"@en ;
     dc:relation oke:184_191_Al_Gore ;
     owl:sameAs dbpedia:Al_Gore .

oke:184_191_Al_Gore
     a nif:OffsetBasedString ;
     nif:referenceContext oke:sentence-2 ;
     nif:beginIndex "184"^^xsd:int ;
     nif:endIndex "191"^^xsd:int .
```

**Comment by anuzzolese** [comment]
Hi Julien,

thanks for your feedback.
I noticed you changed all the full qualified URIs with namespace prefixes.
You also referred to some typos you fixed in the file. Could you please point out what are such typos?

## 

Andrea

**Comment by jplu** [comment]
Hi,

Ok, there is some missing dots in the prefix declarations, for `d0`, `dul` and `dc`. For `d0` there is a missing `#` as well. And all the `oke` URIs where like this `<http://www.ontologydesignpatterns.org/data/oke-challenge/...>` instead of being like this `<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/...>`.

**Comment by jplu** [comment]
Hi,

The file is still not valid, there is some typos in the new version:
- `@prefix d0: <http://ontologydesignpatterns.org/ont/wikipedia/d0.owl> .` should be `@prefix d0: <http://ontologydesignpatterns.org/ont/wikipedia/d0.owl#> .`.
- the prefix `itsrdf` is not defined, should be `http://www.w3.org/2005/11/its/rdf#`
- since RDF 1.1 it is useless to add "^^xsd:string" at the end of a string, better to add "@en" instead.

I hope those new comments will be useful :-)

**Comment by jplu** [comment]
There is also few errors more:
- in the `endIndex` values, each there is a too much +1 as we start from 0
- `Sydney` appears twice instead of `Douglas Robert Dundas`
- there is still the `/task-1/` missing in the `oke` URIs

A corrected file could be this one:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix d0: <http://ontologydesignpatterns.org/ont/wikipedia/d0.owl#> .
@prefix dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#> .
@prefix oke: <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/> .
@prefix dbpedia: <http://dbpedia.org/resource/> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=0,160>
        a               nif:RFC5147String , nif:String , nif:Context ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "160"^^xsd:nonNegativeInteger ;
        nif:isString    "Florence May Harding studied at the National Art School in Sydney, and with Douglas Robert Dundas , but in effect had no formal training in either botany or art."@en .

oke:Florence_May_Harding
     a        dul:Person ;
     rdfs:label "Florence May Harding"@en ;
     owl:sameAs dbpedia:Florence_May_Harding .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=0,19>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "Florence May Harding"@en ;
        nif:beginIndex        "0"^^xsd:nonNegativeInteger ;
        nif:endIndex          "19"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=0,160> ;
        itsrdf:taIdentRef     oke:Florence_May_Harding .

oke:National_Art_School
     a        dul:Organization ;
     rdfs:label "National Art School"@en ;
     owl:sameAs dbpedia:National_Art_School .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=36,54>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "National Art School"@en ;
        nif:beginIndex        "36"^^xsd:nonNegativeInteger ;
        nif:endIndex          "54"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=0,160> ;
        itsrdf:taIdentRef     oke:National_Art_School .

oke:Sydney
     a        d0:Location ;
     rdfs:label "Sydney"@en ;
     owl:sameAs dbpedia:Sydney .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=59,64>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "Sydney"@en ;
        nif:beginIndex        "59"^^xsd:nonNegativeInteger ;
        nif:endIndex          "64"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=0,160> ;
        itsrdf:taIdentRef     oke:Sydney .

oke:Douglas_Robert_Dundas
     a        dul:Person ;
     rdfs:label "Douglas Robert Dundas"@en .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=76,96>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "Douglas Robert Dundas"@en ;
        nif:beginIndex        "76"^^xsd:nonNegativeInteger ;
        nif:endIndex          "96"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-1#char=0,160> ;
        itsrdf:taIdentRef     oke:Douglas_Robert_Dundas .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=0,191>
        a               nif:RFC5147String , nif:String , nif:Context ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "191"^^xsd:nonNegativeInteger ;
        nif:isString    "Such notables include James Carville, who was the senior political adviser to Bill Clinton, and Donna Brazile, the campaign manager of the 2000 presidential campaign of Vice-President Al Gore."@en .

oke:James_Carville
     a        dul:Person ;
     rdfs:label "James Carville"@en ;
     owl:sameAs dbpedia:James_Carville .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=22,35>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "James Carville"@en ;
        nif:beginIndex        "22"^^xsd:nonNegativeInteger ;
        nif:endIndex          "35"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=0,191> ;
        itsrdf:taIdentRef     oke:James_Carville .

oke:Political_adviser
     a        dul:Role ;
     rdfs:label "political adviser"@en ;
     owl:sameAs dbpedia:Political_consulting .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=57,73>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "political adviser"@en ;
        nif:beginIndex        "57"^^xsd:nonNegativeInteger ;
        nif:endIndex          "73"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=0,191> ;
        itsrdf:taIdentRef     oke:Political_adviser .

oke:Bill_Clinton
     a        dul:Person ;
     rdfs:label "Bill Clinton"@en ;
     owl:sameAs dbpedia:Bill_Clinton .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=78,89>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "Bill Clinton"@en ;
        nif:beginIndex        "78"^^xsd:nonNegativeInteger ;
        nif:endIndex          "89"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=0,191> ;
        itsrdf:taIdentRef     oke:Bill_Clinton .

oke:Donna_Brazile
     a        dul:Person ;
     rdfs:label "Donna Brazile"@en ;
     owl:sameAs dbpedia:Donna_Brazile . 

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=96,108>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "Donna Brazile"@en ;
        nif:beginIndex        "96"^^xsd:nonNegativeInteger ;
        nif:endIndex          "108"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=0,191> ;
        itsrdf:taIdentRef     oke:Donna_Brazile .

oke:Campaign_manager
     a        dul:Role ;
     rdfs:label "campaign manager"@en ;
     owl:sameAs dbpedia:Campaign_manager .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=115,130>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "campaign manager"@en ;
        nif:beginIndex        "115"^^xsd:nonNegativeInteger ;
        nif:endIndex          "130"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=0,191> ;
        itsrdf:taIdentRef     oke:Campaign_manager .

oke:Al_Gore
     a        dul:Person ;
     rdfs:label "Al Gore"@en ;
     owl:sameAs dbpedia:Al_Gore .

<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=184,190>
        a                     nif:RFC5147String , nif:String ;
        nif:anchorOf          "Al Gore"@en ;
        nif:beginIndex        "184"^^xsd:nonNegativeInteger ;
        nif:endIndex          "190"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-2#char=0,191> ;
        itsrdf:taIdentRef     oke:Al_Gore .
```

Hope this help^^

**Comment by MichaelRoeder** [comment]
Sorry for all the new typos :(

@jplu : Sorry, but I am afraid, that I disagree with your comment regarding the end positions. Following the NIF Standard ( http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core/nif-core.html#endIndex ) that follows RFC 5147 ( http://tools.ietf.org/html/rfc5147#section-2.2.1 ) the index counts are not characters, but character positions. Thus, if a string has n characters it contains n+1 character positions ranging from 0 to n. Since, "Florence May Harding" has 20 characters, its beginIndex is 0 and its endIndex is 20.
Or got I something wrong?

**Comment by jplu** [comment]
Ah ok, it is really not logic to me but well, never mind.

**Comment by anuzzolese** [comment]
Sorry,

it was my fault as I didn’t check the new version of the example proposed by Julien.
I agree with Michael, hence, for example, the endIndex of "Florence May Harding” is 20.
I am going to fix the example.

## 

Andrea
